---
- name: Create an s3 bucket on AWS with Ansible
  hosts: localhost
  connection: local
  
  vars:
      hereorthere: "present"

  tasks:
          - name: installing aws pre-req
            pip: 
              name: boto
              state: present
              
          - name: creating an s3 bucket
            s3_bucket:
              name: ducktoaster77    # naming rules https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules
              state: "{{ hereorthere }}"
              aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
              aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
            